url: https://radish-bdd.github.io
baseurl:

# Site settings
title: radish
slogan: the root from red to green
email: tuxtimo@gmail.com
description: "Awesome python BDD tool and more"

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary: fed136
  #secondary: fec503
  primary: c40a18
  secondary: c51c2f
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/radish-bdd
  - title: twitter
    url: http://twitter.com/tuxtimo

# Build settings
markdown: kramdown
permalink: pretty
